config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get    "tasks",          to: "tasks#index"
  # Create
  get    "tasks/new",      to: "tasks#new",  as: :new_restaurant
  post   "tasks",          to: "tasks#create"
  # Read one - The `show` route needs to be *after* `new` route.
  get    "tasks/:id",      to: "tasks#show", as: :restaurant
  # Update
  get    "tasks/:id/edit", to: "tasks#edit", as: :edit_restaurant
  patch  "tasks/:id",      to: "tasks#update"
  # Delete
  delete "tasks/:id",      to: "tasks#destroy"
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]

  def index
    # See all restaurants
    @tasks = Task.all
  end

  def show
    # See details about one restaurant
    set_task
  end

  def new
    # Create a restaurant (I)
    @task = Task.new
  end

  def create
    # Create a restaurant (II)
    @task = Task.new(task_params)
    # raise
    @task.save
    redirect_to task_path
  end

  def edit
    # Update a restaurant (I)
    set_task
  end

  def update
    # Update a restaurant (II)
    set_task
    @task.update(task_params)
    redirect_to task_path
  end

  def destroy
    # Destroy a restaurant
    set_task
    @task.destroy
    redirect_to task_path, status: :see_other
  end

  def check_box(object_name, method, options = {}, checked_value = '1', unchecked_value = '0')
    Tags::CheckBox.new(object_name, method, self, checked_value, unchecked_value, options).render
  end


  private

  def task_params
    # Protects against CRLF injection
    params.require(:task).permit(:title, :details, :completed) #:tables
  end

  def set_task
    # Finds model per id
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_checkbox.html.erb
<%= form_with model: task do |f| %>
  <%= f.label :completed %>
  <%= f.check_box :completed%>
  <%= f.submit %>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: task do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.label :details %>
  <%= f.text_field :details %>
  <%= f.label :completed %>
  <%= f.check_box :completed %>
  <%= f.submit %>
<% end %>

app/views/tasks/edit.html.erb
<%= render "form", task: @task %>

app/views/tasks/index.html.erb
<h3> All Tasks </h3>

<ul>
  <% @tasks.each do |task| %>
  <h2><%= link_to task.title, task_path(task)%></h2>
  <p> Completed? <%= task.completed ? "Yes" : "No" %></p>
  <p>Details:<br><%= task.details %></p>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<%= render "form", task: @task %>

app/views/tasks/show.html.erb
<h2><%= @task.title %></h2>
<p> Completed? <%= @task.completed ? "Yes" : "No" %></p>
<p>Details:<br><%= @task.details %></p>

<p>links:</p>
<p><%= link_to "Home", tasks_path %> </p>
<p><%= link_to "Edit", edit_task_path %> </p>
<p><%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}
  %>
  </p>

make these into cards later